import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { createServer } from 'node:http';
import { test } from 'node:test';
import { chromium, expect } from '@playwright/test';
import { initialBundle, type Workspace } from '../shared/commands/model';

test('桌面与移动端命令编辑、试跑、发布、回滚和运行时模型设置', { timeout: 60000 }, async () => {
  const generatedBundle = initialBundle('浏览器生成草稿');
  const model = createServer(async (request, response) => {
    for await (const _chunk of request) { /* 读取请求后返回确定性测试草稿。 */ }
    response.writeHead(200, { 'content-type': 'application/json' });
    response.end(JSON.stringify({ status: 'completed', output: [{ type: 'message', content: [{ type: 'output_text', text: JSON.stringify(generatedBundle) }] }] }));
  });
  await new Promise<void>(resolve => model.listen(0, '127.0.0.1', resolve));
  const browser = await chromium.launch({ headless: true });
  const errors: string[] = [];
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    page.on('pageerror', error => errors.push(error.message));
    const base = process.env.VIBECLI_TEST_UI_URL || 'http://127.0.0.1:8791';
    await page.goto(base);
    await page.getByRole('button', { name: '新增命令集', exact: true }).first().click();
    const dialog = page.getByRole('dialog', { name: '新建命令集' });
    const title = `界面验收 ${Date.now()}`;
    await dialog.getByLabel('命令集名称').fill(title);
    await dialog.getByRole('button', { name: '创建', exact: true }).click();
    await expect(page.getByLabel('命令路径')).toHaveValue('greet');
    const source = page.getByRole('textbox', { name: '执行逻辑', exact: true });
    const undo = page.getByRole('button', { name: '撤销', exact: true });
    const redo = page.getByRole('button', { name: '重做', exact: true });
    await expect(page.locator('.source-editor .cm-editor')).toBeVisible();
    await expect(page.locator('.source-editor .cm-lineNumbers')).toBeVisible();
    await expect(source).toHaveAttribute('contenteditable', 'true');
    await expect(source).toHaveText(generatedBundle.commands[0]!.source);
    await expect(undo).toBeDisabled();
    await expect(redo).toBeDisabled();
    await page.getByRole('button', { name: '查找', exact: true }).click();
    const search = page.locator('.cm-search input[name="search"]');
    await expect(search).toBeVisible();
    await search.fill('Hello');
    await search.press('Enter');
    await expect(page.locator('.cm-searchMatch').first()).toBeVisible();
    await search.press('Escape');
    await expect(page.locator('.cm-search')).toHaveCount(0);
    const wrap = page.getByRole('button', { name: '自动换行', exact: true });
    const initiallyWrapped = await wrap.getAttribute('aria-pressed');
    assert.ok(initiallyWrapped === 'true' || initiallyWrapped === 'false');
    await wrap.click();
    await expect(wrap).toHaveAttribute('aria-pressed', initiallyWrapped === 'true' ? 'false' : 'true');
    await wrap.click();
    await expect(wrap).toHaveAttribute('aria-pressed', initiallyWrapped);
    await page.getByRole('button', { name: '验证', exact: true }).first().click();
    await expect(page.getByText('全部通过', { exact: true })).toBeVisible();
    await page.getByRole('button', { name: '运行', exact: true }).click();
    await expect(page.locator('.execution-output pre').first()).toHaveText('Hello, Ada!');
    await page.getByRole('button', { name: '发布', exact: true }).click();
    await expect(page.getByText('版本已发布', { exact: true })).toBeVisible();
    await page.getByRole('tab', { name: '逻辑', exact: true }).click();
    await page.getByLabel('命令路径').fill('wave');
    const editedSource = 'return "Hi " + input.name;';
    await source.fill(editedSource);
    await expect(source).toHaveText(editedSource);
    await expect(undo).toBeEnabled();
    await undo.click();
    await expect(source).toHaveText(generatedBundle.commands[0]!.source);
    await expect(redo).toBeEnabled();
    await redo.click();
    await expect(source).toHaveText(editedSource);
    await source.fill('return (;');
    await expect(page.locator('.cm-lintRange-error').first()).toBeVisible();
    await source.fill(editedSource);
    await expect(source).toHaveText(editedSource);
    await expect(page.locator('.cm-lintRange-error')).toHaveCount(0);
    await source.fill('return input.na');
    await expect(source).toHaveText('return input.na');
    await source.press('Control+Space');
    const completions = page.locator('.cm-tooltip-autocomplete');
    await expect(completions).toBeVisible();
    await completions.getByRole('option').filter({ hasText: 'name' }).click();
    await expect(source).toHaveText('return input.name');
    await page.getByLabel('名称', { exact: true }).fill('release-date');
    await source.fill('return input["rel"]');
    await expect(source).toHaveText('return input["rel"]');
    await source.press('End');
    await source.press('ArrowLeft');
    await source.press('ArrowLeft');
    await source.press('Control+Space');
    await expect(completions).toBeVisible();
    await completions.getByRole('option').filter({ hasText: 'release-date' }).click();
    await expect(source).toHaveText('return input["release-date"]');
    await source.fill('return input["rel" ]');
    await expect(source).toHaveText('return input["rel" ]');
    await source.press('End');
    await source.press('ArrowLeft');
    await source.press('ArrowLeft');
    await source.press('ArrowLeft');
    await source.press('Control+Space');
    await expect(completions).toBeVisible();
    await completions.getByRole('option').filter({ hasText: 'release-date' }).click();
    await expect(source).toHaveText('return input["release-date"]');
    await page.getByLabel('名称', { exact: true }).fill('name');
    await source.fill(editedSource);
    await expect(source).toHaveText(editedSource);
    let releaseSave!: () => void;
    const saving = new Promise<void>(resolve => { releaseSave = resolve; });
    await page.route('**/api/projects/*', async route => {
      if (route.request().method() === 'PUT') {
        await saving;
      }
      await route.continue();
    });
    try {
      await page.getByRole('button', { name: '保存', exact: true }).click();
      await expect(source).toHaveAttribute('contenteditable', 'false');
      await expect(undo).toBeDisabled();
      await expect(redo).toBeDisabled();
      // 只读内容不在焦点顺序中，直接送达编辑器键盘处理器验证禁用期间的撤销边界。
      await source.dispatchEvent('keydown', { key: 'z', code: 'KeyZ', metaKey: process.platform === 'darwin', ctrlKey: process.platform !== 'darwin' });
      await expect(source).toHaveText(editedSource);
    } finally {
      releaseSave();
    }
    await expect(page.getByText('草稿已保存', { exact: true })).toBeVisible();
    await expect(source).toHaveAttribute('contenteditable', 'true');
    await expect(source).toHaveText(editedSource);
    await expect(undo).toBeEnabled();
    await page.unroute('**/api/projects/*');
    await page.getByRole('button', { name: '新增命令', exact: true }).click();
    await expect(page.getByLabel('命令路径')).toHaveValue('command');
    await expect(source).toHaveText('return "";');
    await expect(undo).toBeDisabled();
    await expect(redo).toBeDisabled();
    await source.fill('return "Other";');
    await expect(undo).toBeEnabled();
    await undo.click();
    await expect(source).toHaveText('return "";');
    await page.getByRole('navigation', { name: '命令', exact: true }).getByRole('button', { name: 'wave', exact: true }).click();
    await expect(source).toHaveText(editedSource);
    await expect(undo).toBeDisabled();
    await expect(redo).toBeDisabled();
    await page.getByRole('navigation', { name: '命令', exact: true }).getByRole('button', { name: 'command', exact: true }).click();
    await expect(source).toHaveText('return "";');
    await page.getByRole('button', { name: '删除命令', exact: true }).click();
    await page.getByRole('dialog', { name: '删除此命令？' }).getByRole('button', { name: '删除', exact: true }).click();
    await expect(source).toHaveText(editedSource);
    await page.getByLabel('预期标准输出').fill('Hi Ada\n');
    await page.getByRole('button', { name: '验证', exact: true }).first().click();
    await expect(page.getByText('全部通过', { exact: true })).toBeVisible();
    await page.getByRole('button', { name: '运行', exact: true }).click();
    await expect(page.locator('.execution-output pre').first()).toHaveText('Hi Ada');
    await page.getByRole('button', { name: '发布', exact: true }).click();
    await expect(page.getByText('版本已发布', { exact: true })).toBeVisible();
    await page.getByRole('tab', { name: '版本', exact: true }).click();
    await expect(page.locator('.revision-row')).toHaveCount(2);
    await page.getByRole('button', { name: '启用此版本', exact: true }).click();
    await page.getByRole('dialog', { name: '切换发布版本？' }).getByRole('button', { name: '确认', exact: true }).click();
    await expect(page.getByText('已切换发布版本', { exact: true })).toBeVisible();
    const workspace = await (await page.request.get(`${base}/api/projects`)).json() as Workspace;
    const project = workspace.projects.find(value => value.title === title)!;
    const invoked = await (await page.request.post(`${base}/api/cli/${project.id}/invoke`, { data: { argv: ['greet', '--name', 'Ada'] } })).json();
    assert.equal(invoked.stdout, 'Hello, Ada!\n');
    await page.getByRole('tab', { name: '逻辑', exact: true }).click();
    await page.getByRole('button', { name: 'AI 设置', exact: true }).click();
    const settings = page.getByRole('dialog', { name: 'AI 设置' }).first();
    await settings.getByLabel('模型入口', { exact: true }).fill(`http://127.0.0.1:${(model.address() as { port: number }).port}/v1`);
    await settings.getByLabel('模型', { exact: true }).fill('test-browser-generator');
    await settings.getByRole('button', { name: '保存', exact: true }).click();
    await expect(page.getByText('AI 设置已保存', { exact: true })).toBeVisible();
    await page.getByLabel('AI 意图', { exact: true }).fill('生成问候命令');
    await page.getByRole('button', { name: '生成草稿', exact: true }).click();
    await expect(page.getByRole('dialog', { name: '审核生成草稿' })).toBeVisible();
    await page.getByRole('button', { name: '采用草稿', exact: true }).click();
    await expect(page.getByLabel('命令集名称')).toHaveValue('浏览器生成草稿');
    await expect(page.getByLabel('命令路径')).toHaveValue('greet');
    await expect(source).toHaveText(generatedBundle.commands[0]!.source);
    await expect(undo).toBeDisabled();
    await expect(redo).toBeDisabled();
    await page.getByRole('tab', { name: '文档', exact: true }).click();
    await expect(page.locator('.document-content')).toContainText('aio greet --name');
    await page.getByRole('tab', { name: '逻辑', exact: true }).click();
    await mkdir('test-results', { recursive: true });
    await page.screenshot({ path: 'test-results/desktop.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await source.scrollIntoViewIfNeeded();
    await expect(source).toBeVisible();
    await expect(page.locator('.source-editor .cm-editor')).toBeVisible();
    await expect(source).toHaveText(generatedBundle.commands[0]!.source);
    await page.screenshot({ path: 'test-results/mobile.png', fullPage: true });
    const geometry = await page.evaluate(() => ({ width: document.documentElement.clientWidth, scrollWidth: document.documentElement.scrollWidth }));
    assert.ok(geometry.scrollWidth <= geometry.width + 1, JSON.stringify(geometry));
    await page.getByRole('button', { name: '连接 CLI', exact: true }).click();
    await expect(page.getByRole('dialog', { name: '连接 CLI' })).toBeVisible();
    await page.screenshot({ path: 'test-results/mobile-dialog.png', fullPage: true });
    assert.deepEqual(errors, []);
  } finally {
    await browser.close();
    await new Promise<void>(resolve => model.close(() => resolve()));
  }
});
