export const text = {
  brand: 'VibeCLI', workspace: '命令工作台', projects: '命令集', commands: '命令',
  addProject: '新增命令集', addCommand: '新增命令', newProject: '新建命令集',
  projectTitle: '命令集名称', projectPlaceholder: '例如：日常开发工具', create: '创建',
  save: '保存', saving: '保存中', verify: '验证', verifying: '验证中',
  publish: '发布', publishing: '发布中', connect: '连接 CLI', cancel: '取消',
  close: '关闭', confirm: '确认', delete: '删除', removeCommand: '删除命令',
  deleteTitle: '删除此命令？', deleteBody: '删除后需要保存，才会更新命令集草稿。',
  discardTitle: '离开当前草稿？', discardBody: '当前修改尚未保存，离开后将丢弃这些修改。',
  discard: '丢弃并继续', draft: '草稿', unsaved: '未保存', saved: '已保存',
  unpublished: '未发布', published: '已发布', active: '当前版本', development: '本机开发',
  loading: '正在加载命令集', retry: '重试', loadError: '命令集加载失败',
  noProjects: '暂无命令集', noCommands: '暂无命令', emptyCommand: '选择或新增命令',
  logic: '逻辑', documentation: '文档', preview: '试跑', versions: '版本',
  path: '命令路径', pathPlaceholder: '例如：project status', description: '说明',
  descriptionPlaceholder: '此命令的用途', usage: '用法', parameters: '参数',
  addParameter: '新增参数', parameterName: '名称', parameterType: '类型',
  required: '必填', positional: '位置参数', parameterDescription: '参数说明',
  defaultValue: '默认值', hasDefault: '设置默认值', removeParameter: '删除参数',
  stringType: '文本', numberType: '数字', booleanType: '布尔',
  source: '执行逻辑', sourceLanguage: 'JavaScript', examples: '示例与预期',
  undo: '撤销', redo: '重做', find: '查找', wrap: '自动换行', syntaxError: '语法错误',
  addExample: '新增示例', removeExample: '删除示例', example: '示例',
  arguments: '参数值', addArgument: '新增参数值', removeArgument: '删除参数值',
  argumentPlaceholder: '参数或值', stdout: '标准输出', stderr: '错误输出',
  expectedStdout: '预期标准输出', expectedExit: '预期退出码', exitCode: '退出码',
  download: '下载文档', generatedDocument: '草稿文档', run: '运行', running: '运行中',
  noOutput: '暂无输出', noResult: '尚未运行', chooseExample: '示例', manualArguments: '自定义',
  verification: '示例验证', verified: '全部通过', verificationFailed: '验证未通过',
  verificationStale: '草稿已变更，请重新验证', noVerification: '尚未验证',
  expected: '预期', actual: '实际', passed: '通过', failed: '失败',
  fixFailures: '根据失败结果修正', fixIntent: '根据验证失败修复命令，保持其余用法。',
  aiIntent: 'AI 意图', aiPlaceholder: '例如：新增一个根据日期生成发布版本号的命令',
  generate: '生成草稿', generating: '生成中', aiUnavailable: 'AI 尚未配置',
  generationTitle: '审核生成草稿', adopt: '采用草稿', generatedCommands: '生成的命令',
  generatedChanged: '生成期间当前草稿已有修改。',
  replaceTitle: '替换当前草稿？', replaceBody: '采用后会替换当前未保存的修改。',
  aiFeedback: '已携带失败反馈', clearFeedback: '清除反馈',
  noVersions: '暂无发布版本', revision: '版本', createdAt: '发布时间',
  rollback: '启用此版本', activating: '切换中', rollbackTitle: '切换发布版本？',
  rollbackBody: 'CLI 后续执行将使用此版本。',
  connectionTitle: '连接 CLI', connectionCommand: '连接命令', connectionEndpoint: 'CLI 入口',
  connectionPending: '正式 CLI 入口尚未提供', connectionPendingBody: '需要宿主提供正式 CLI 入口。',
  localConnection: '本机开发入口', connectionVersion: '执行版本', copy: '复制', copied: '已复制',
  localMode: '本机', aioMode: 'AIO 已安装', hostOrigin: '宿主地址', sourceId: '插件 source UUID',
  account: '账号', loginCommand: '登录命令', hostPlaceholder: 'https://aio.example.com',
  accountPlaceholder: '账号名称', sourcePlaceholder: '插件的 source UUID',
  loginRequired: '先登录，再连接命令集', connectionInputsMissing: '填写宿主地址与 source UUID',
  exportBundle: '导出命令集', importBundle: '导入命令集', importSuccess: '命令集已导入，尚未保存',
  importError: '命令集文件无效', importTitle: '导入此命令集？',
  settings: 'AI 设置', configureAi: '配置 AI', endpoint: '模型入口', model: '模型',
  protocol: '协议', apiKey: 'API 密钥', keyStored: '已保存，留空保留', keyPlaceholder: '输入 API 密钥',
  clearKey: '清除密钥', clearKeyTitle: '清除此密钥？', clearKeyBody: '保存设置后，已保存的密钥将被删除。',
  keyCleared: '保存时清除密钥', settingsSaved: 'AI 设置已保存', settingsLoading: '正在读取 AI 设置',
  settingsLoadError: 'AI 设置读取失败', endpointPlaceholder: 'https://api.example.com/v1',
  modelPlaceholder: '模型名称', responsesProtocol: 'Responses', chatProtocol: 'Chat Completions',
  saveSuccess: '草稿已保存', publishSuccess: '版本已发布', activateSuccess: '已切换发布版本',
  generatedSuccess: '生成草稿已采用，尚未保存', verificationSuccess: '所有示例验证通过',
  createSuccess: '命令集已创建', invalidDraft: '草稿定义无效',
  unexpectedError: '操作失败', notFound: '命令集不存在', emptyTitle: '请输入命令集名称',
  untitledCommand: '未命名命令', none: '无', zeroCommands: '0 个命令',
  commandCount: (count: number) => `${count} 个命令`,
  testCount: (passed: number, total: number) => `${passed} / ${total} 通过`,
  exampleNumber: (index: number) => `示例 ${index + 1}`,
  revisionShort: (id: string) => id.slice(0, 10),
} as const;

export const editorPhrases = {
  Find: '查找', Replace: '替换', next: '下一个', previous: '上一个', all: '全部',
  'match case': '区分大小写', regexp: '正则表达式', 'by word': '全词匹配',
  replace: '替换', 'replace all': '替换全部', close: '关闭',
  'Go to line': '跳转到行', go: '跳转', 'Fold line': '折叠行', 'Unfold line': '展开行',
  'No diagnostics': '无诊断', Diagnostics: '诊断',
  'Control character': '控制字符', 'current match': '当前匹配', 'on line': '所在行',
  'replaced match on line $': '已替换第 $ 行匹配', 'replaced $ matches': '已替换 $ 处匹配',
  'Completions': '补全',
};
